apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "template.fullname" . }}-filebeat
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "template.fullname" . }}-filebeat
  labels:
    app: {{ include "template.fullname" . }}-filebeat
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "template.fullname" . }}-filebeat
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "template.fullname" . }}-filebeat