apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "template.fullname" . }}-filebeat-conf
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "template.fullname" . }}-filebeat
    kubernetes.io/cluster-service: "true"
data:
  filebeat.yml: |-
    filebeat.config:
      inputs:
        # Mounted `filebeat-prospectors` configmap:
        path: ${path.config}/prospectors.d/*.yml
        # Reload prospectors configs as they change:
        reload.enabled: false
      modules:
        path: ${path.config}/modules.d/*.yml
        # Reload module configs as they change:
        reload.enabled: false
    processors:
      - add_cloud_metadata:

    cloud.id: ${ELASTIC_CLOUD_ID}
    cloud.auth: ${ELASTIC_CLOUD_AUTH}

    output.logstash:
      hosts: ['{{ .Values.global.logstash_service_endpoint }}:5044']
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "template.fullname" . }}-filebeat-prospectors
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "template.fullname" . }}-filebeat
    kubernetes.io/cluster-service: "true"
data:
  kubernetes.yml: |-
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
        - add_kubernetes_metadata:
            in_cluster: true