apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "template.fullname" . }}-filebeat
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "template.fullname" . }}-filebeat
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      app: {{ include "template.fullname" . }}-filebeat
  template:
    metadata:
      labels:
        app: {{ include "template.fullname" . }}-filebeat
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: {{ include "template.fullname" . }}-filebeat
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: {{ include "template.fullname" . }}-filebeat
        image: {{ .Values.image_filebeat.repository }}:{{ .Values.image_filebeat.tag }}
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        env:
        - name: ELASTICSEARCH_HOST
          value: "{{ .Values.global.elasticsearch_service_endpoint }}"
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: ELASTICSEARCH_PASSWORD
          value: changeme
        - name: ELASTIC_CLOUD_ID
          value:
        - name: ELASTIC_CLOUD_AUTH
          value:
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: {{ include "template.fullname" . }}-filebeat-conf
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: {{ include "template.fullname" . }}-filebeat-prospectors
          mountPath: /usr/share/filebeat/prospectors.d
          readOnly: true
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: {{ include "template.fullname" . }}-filebeat-conf
        configMap:
          defaultMode: 0600
          name: {{ include "template.fullname" . }}-filebeat-conf
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: {{ include "template.fullname" . }}-filebeat-prospectors
        configMap:
          defaultMode: 0600
          name: {{ include "template.fullname" . }}-filebeat-prospectors
      - name: data
        emptyDir: {}
