apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "template.fullname" . }}-metricbeat
  namespace: kube-system
  labels:
    app: {{ include "template.fullname" . }}-metricbeat
spec:
  selector:
    matchLabels:
      app: {{ include "template.fullname" . }}-metricbeat
  template:
    metadata:
      labels:
        app: {{ include "template.fullname" . }}-metricbeat
    spec:
      serviceAccountName: {{ include "template.fullname" . }}-metricbeat
      containers:
      - name: {{ include "template.fullname" . }}-metricbeat
        image: {{ .Values.image_metricbeat.repository }}:{{ .Values.image_metricbeat.tag }}
        args: [
          "-c", "/etc/metricbeat.yml",
          "-e",
        ]
        env:
        - name: ELASTICSEARCH_HOST
          value: elasticsearch-logging
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: ELASTICSEARCH_PASSWORD
          value: changeme
        - name: ELASTIC_CLOUD_ID
          value:
        - name: ELASTIC_CLOUD_AUTH
          value:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/metricbeat.yml
          readOnly: true
          subPath: metricbeat.yml
        - name: modules
          mountPath: /usr/share/metricbeat/modules.d
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: {{ include "template.fullname" . }}-metricbeat-conf
      - name: modules
        configMap:
          defaultMode: 0600
          name: {{ include "template.fullname" . }}-metricbeat-deployment-modules
