apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "template.fullname" . }}-metricbeat
subjects:
- kind: ServiceAccount
  name: metricbeat
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: metricbeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "template.fullname" . }}-metricbeat
  labels:
    app: {{ include "template.fullname" . }}-metricbeat
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - events
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "template.fullname" . }}-metricbeat
  namespace: kube-system
  labels:
    app: {{ include "template.fullname" . }}-metricbeat

