apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.global.kibana_service_endpoint }}"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "template.fullname" . }}-kibana
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Kibana"
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "template.fullname" . }}-kibana
