apiVersion: v1
name: ElkCluster
appVersion: "1.0"
description: A Helm deployment for an ELK HA Cluster on K8s 
version: 1.0.0
type: application

dependencies:
  - name: elasticsearch
    version: 1.0.0
    repository: "file://./dependency_charts/elasticsearch"
  - name: logstash
    version: 1.0.0
    repository: "file://./dependency_charts/logstash"
  - name: kibana
    version: 1.0.0
    repository: "file://./dependency_charts/kibana"
  - name: beats
    version: 1.0.0
    repository: "file://./dependency_charts/beats"


