apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "template.fullname" . }}-elasticsearch
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "template.fullname" . }}-elasticsearch
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "template.fullname" . }}-elasticsearch
  labels:
    app: {{ include "template.fullname" . }}-elasticsearch
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - "services"
  - "namespaces"
  - "endpoints"
  verbs:
  - "get"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "template.fullname" . }}-elasticsearch
  labels:
    app: {{ include "template.fullname" . }}-elasticsearch
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: {{ include "template.fullname" . }}-elasticsearch
  namespace: {{ .Values.namespace }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ include "template.fullname" . }}-elasticsearch
  apiGroup: ""
