apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.global.elasticsearch_service_endpoint }}"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "template.fullname" . }}-elasticsearch
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
spec:
  ports:
  - port: {{ .Values.service.db_port }}
    protocol: TCP
    targetPort: db
  selector:
    app: {{ include "template.fullname" . }}-elasticsearch
