apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "template.fullname" . }}-logstash
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "template.fullname" . }}-logstash
  template:
    metadata:
      labels:
        app: {{ include "template.fullname" . }}-logstash
    spec:
      affinity:
       podAntiAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
         - labelSelector:
             matchExpressions:
             - key: app
               operator: In
               values:
               - {{ include "template.fullname" . }}-logstash
           topologyKey: kubernetes.io/hostname
      containers:
      - name: {{ include "template.fullname" . }}-logstash
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.port }}
        volumeMounts:
          - name: config-volume
            mountPath: /usr/share/logstash/config
          - name: logstash-pipeline-volume
            mountPath: /usr/share/logstash/pipeline
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "template.fullname" . }}-logstash
          items:
            - key: logstash.yml
              path: logstash.yml
      - name: logstash-pipeline-volume
        configMap:
          name: {{ include "template.fullname" . }}-logstash
          items:
            - key: logstash.conf
              path: logstash.conf
