kind: Service
apiVersion: v1
metadata:
  name: "{{ .Values.global.logstash_service_endpoint }}"
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "template.fullname" . }}-logstash
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  type: ClusterIP
