apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "template.fullname" . }}-logstash
  namespace: {{ .Values.namespace }}
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    # all input will come from filebeat, no local logs
    input {
      beats {
        port => 5044
      }
    }
    filter {
      if [message] =~ /^\{.*\}$/ {
        json {
          source => "message"
          ecs_compatibility => disabled
        }
      }
      if [ClientHost] {
        geoip {
          source => "ClientHost"
          ecs_compatibility => disabled
        }
      }
    }
    output {
        elasticsearch {
            hosts => [ "http://{{ .Values.global.elasticsearch_service_endpoint }}:9200" ]
        }
    }
